#! /bin/sh

~/.fehbg &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d i ii iii iv v vi vii viii
bspc monitor eDP-1 -d ix x

bspc config top_padding			32

bspc config border_width		2
bspc config window_gap			16

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		false

bspc config normal_border_color		"#2e3440"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

bspc config focus_follows_pointer	true
bspc config pointer_action1		resize_corner
bspc config pointer_action2		move
bspc config pointer_action3		resize_side

bspc rule -a Screenkey manage=off

bspc monitor eDP-1 -s HDMI-1
