#!/bin/sh
#    ░█▀▄░█▀▀░█▀█░█░█░█▄█
#    ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#    ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀

# polybar: x_bar_one is for eDP1, x_bar_two is for HDMI1
killall polybar

case $(bspc query -M | wc -l) in
1)
	# desktops
	bspc monitor eDP1 -d i ii iii iv v vi vii viii ix x
	bspc config window_gap			16
	# polybar
	polybar center_bar_one &
	polybar right_bar_one &
	polybar left_bar_one &
	;;
2)
	# monitor stuff
	xrandr --output HDMI1 --mode 2560x1440
	xrandr --output eDP1 --mode 1366x768
	xrandr --output eDP1 --left-of HDMI1
	xrandr --output HDMI1 --primary
	# desktops
	bspc monitor HDMI1 -d i ii iii iv v vi vii viii
	bspc monitor eDP1 -d ix x
	bspc wm -O HDMI1 eDP1
	bspc config window_gap			32
	# polybar
	polybar center_bar_two &
	polybar right_bar_two &
	polybar left_bar_two &
	;;
esac

# set colorscheme
wal -R

# keyboard config
killall xcape
xmodmap ~/scripts/swap_ctrl_caps
xcape -e 'Control_L=Escape' &
xcape -e 'Shift_L=Shift_L|9;Shift_R=Shift_R|0' &

killall mpd
mpd &

# for some reason apparently killall kills the picom right after it?
# need to do some tests
killall picom && sleep 0.25
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

# killall bb.sh && sleep 0.25
# ~/scripts/bb.sh &

killall blurwal
blurwal -m 1 -b 6 &

# padding and stuff
bspc config top_padding			42
bspc config border_width		2

# various settings
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		false

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# set colors
bspc config normal_border_color "$background"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

# this was for nord
# bspc config normal_border_color	"#2e3440"
# bspc config focused_border_color	"#88c0d0"
# bspc config presel_feedback_color	"#88c0d0"

# rules
bspc rule -a Polybar layer=BELOW
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
